//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Copies = new HashSet<Copies>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public int NumberOfCopies { get; set; }
        public int AvailableCopies { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Copies> Copies { get; set; }
    }
}
