//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowedBook
    {
        public int BorrowedBookId { get; set; }
        public Nullable<int> BorrowerId { get; set; }
        public System.DateTime BorrowedDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public bool IsReturned { get; set; }
        public Nullable<int> CopyId { get; set; }
    
        public virtual Borrowers Borrowers { get; set; }
        public virtual Copies Copies { get; set; }
    }
}
